### ISSUE TITLE
Make docker-compose up work when go-ipfs/ipfs-desktop is running 

### ISSUE THREAD

**Issue by lidel** [andrew/pinning-api#7]
Right now `docker-compose up` fails to start if something runs on popular default ports `4001, 8080, 5001`  (eg go-ipfs, ipfs-desktop, or any http server on `8080`)

@andrew  Would it be possible to switch defaults away to different ones to remove the friction caused by port conflict?

**Comment by andrew** [comment]
Yeah I don't see why not, any suggestions or just some random numbers?

**Comment by lidel** [comment]
Random numbers would be the best.

**Comment by andrew** [comment]
Instead of changing the port numbers, I've just made docker stop exposing the internal ipfs daemon to the public.
