### ISSUE TITLE
Immediate pin of inlined cids

### ISSUE THREAD

**Issue by lidel** [andrew/pinning-api#8]
> I think if we can make [rb-pinning-service-api](https://github.com/ipfs-shipyard/rb-pinning-service-api) immediately return inlined CIDs (example: `bafkqaaa`  – empty identity hash)  in "pinned" status (because no data needs to be fetched, its inlined in the CID), then we have means of testing `--background=false` on CI reliably without worrying about data transfer working in  GithubAction + docker setup

Ref. 

- passing  `ipfs add --inline --inline-limit 100` will enable inlining of up to 100 bytes of data into CID itself
- https://cid.ipfs.io/#bafkqaaa
- https://cid.ipfs.io/#z45btRgLsWtUjnxUC6eCo1EWfquee6nzwdLPDGyM7YAjiZHn6iArvVr546aaCXwsinDV7pLuzx3CfM7KiAXqf9CcqjjfVU9g4toFd9VE7VMASTrxDYWCzohasmJy1CbGhoArqQp5PyNPC6SBMYMqPQsGuUNXAtEBphybn9xRw3q9U7uyw77gMz3RzRSCo5D7nd6F3KcoQYuxD6NoGuqFuYoE2PHhZLksDd5StdH2a69WEWF2Y9RP1ZMZ5igg8XZH6DREV3h3

@andrew is this feasible? :pray:

**Comment by andrew** [comment]
Yep this is do-able, will use https://github.com/multiformats/ruby-multihash to check the hash when saving and set status as pinned if code is 0x00: 

```
out = Multihashes.decode multihash_binary_string
# => {:code=>18, :hash_function=>"sha2-256", :length=>32, :digest=>"\x14'\x11\xD3\x8C\xA7\xA3<R\x18Ao\x8F\xFC\xC6FH\xCAF\x16\xA6%\xB5\xE0\xA0\xAB=\xA1\x91\x1D]z"}
```
