### ISSUE TITLE
Deterministic docker-compose.yml for use in CI

### ISSUE THREAD

**Issue by lidel** [andrew/pinning-api#9]
@andrew  would it be possible for you to manually make and publish a `v0.0.1` or something at https://hub.docker.com/r/ipfsshipyard/rb-pinning-service-api/tags?

I am planning to simplify go-ipfs CI with  https://github.com/ipfs-shipyard/js-mock-ipfs-pinning-service but if that does not work out or takes too long would like to unblock merging of https://github.com/ipfs/go-ipfs/pull/7661 by making `rb-pinning-service-api`  deterministic. 

For that to work, we need to create separate `deterministic` branch in this repo which replaces use of `latest` tag in `docker-compose.yml` with static versions.

**Comment by andrew** [comment]
published tag to docker hub as v0.1.0: https://hub.docker.com/layers/ipfsshipyard/rb-pinning-service-api/v0.1.0/images/sha256-ba54792336c70b13146a3a66b3bda8e01590c98c90d9e74097da67e04bbd2b90?context=explore 

Updated docker-compose.yml to use tag here: https://github.com/ipfs-shipyard/rb-pinning-service-api/commit/773c3adbb421c551d2d89288abac3e01e1f7c3a8
